backend:
  name: github
  repo: stevencaputo/cucina-dei-ribelli   # Replace with your GitHub username and repository name
  client_id: Ov23li93fIi6DB5mG5Vc
branch: main                         # Replace with your default branch if different
media_folder: "/images/"         # Folder where uploaded images will be stored
public_folder: "/images/"
collections:
  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"          # Folder to store recipe files (Markdown, for example)
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["Aperitivo", "Antipasti", "Primi", "Secondi", "Contorni", "Insalata", "Dolce", "Digestivo"] }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "ingredients", label: "Ingredients", widget: "list" }
      - { name: "instructions", label: "Instructions", widget: "markdown" }
